[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "geohazard-representation"
version = "0.1.0"
description = "Regular spatial representation and interpolation of geohazard data"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "h5py"
]
